from .utils import get_system_font, get_monospace_font, s

colors = {

    "white": "#ffffff",
    "black": "#000000",
    "text": "#1d1d1f",
    "text_secondary": "#495057",
    "border": "#e5e5ea",
    "border_light": "#d1d1d6",
    "background_light": "#f2f2f7",
    "background_very_light": "#f8f9fa",
    "background_gray": "#e9ecef",
    "primary": "#007AFF",
    "primary_hover": "#0056CC",
    "primary_pressed": "#004499",
    "text_on_primary": "#ffffff",
    "secondary": "#4a90e2",
    "secondary_hover": "#357abd",
    "secondary_pressed": "#2c5aa0",
    "secondary_dark": "#1e3a5f",
    "success": "#28a745",
    "success_hover": "#218838",
    "success_pressed": "#1e7e34",
    "success_dark": "#155724",
    "danger": "#dc3545",
    "danger_hover": "#c82333",
    "danger_pressed": "#a71e2a",
    "danger_light": "#ffe6e6",
    "danger_very_light": "#fff5f5",
    "text_on_danger": "#721c24",
    "text_on_danger_hover": "#5a1a1f",
    "text_disabled": "#6c757d",
    "terminal_background_start": "#2d3748",
    "terminal_background_end": "#1a202c",
    "terminal_text": "#e2e8f0",
    "terminal_border": "#4a5568",
    "terminal_selection": "#4a90e2",
    "terminal_command": "#66d9ef",
    "log_error": "#ff6b6b",
    "log_warning": "#ffa726",
    "log_success": "#66bb6a",
    "log_info": "#42a5f5",
    "log_timestamp": "#718096",
    "log_command_error": "#f92672",
    "tooltip_background_start": "#ffffff",
    "tooltip_background_end": "#f8f9fa",
    "tooltip_border": "#4a90e2",
    "tooltip_text": "#2c3e50",
    "scrollbar_background_start": "#f8f9fa",
    "scrollbar_background_end": "#e9ecef",
    "scrollbar_background_border": "#e9ecef",
    "scrollbar_handle_start": "#ced4da",
    "scrollbar_handle_end": "#adb5bd",
    "scrollbar_handle_border": "#adb5bd",
    "scrollbar_handle_hover_start": "#4a90e2",
    "scrollbar_handle_hover_end": "#357abd",
    "scrollbar_handle_hover_border": "#357abd",
    "scrollbar_handle_pressed_start": "#2c5aa0",
    "scrollbar_handle_pressed_end": "#1e3a5f",
    "scrollbar_handle_pressed_border": "#1e3a5f",
    "tab_background": "#f1f3f5",
    "tab_border": "#e9ecef",
    "tab_text": "#495057",
    "tab_hover_background": "#e9ecef",
    "tab_selected_background": "#4a90e2",
    "tab_selected_text": "#ffffff",
    "menu_background": "#ffffff",
    "menu_border": "#dcdfe6",
    "menu_item_selected_background": "#4a90e2",
    "menu_item_selected_text": "#ffffff",
    "menu_separator": "#e5e5e5",
    "main_background_start": "#f8f9fa",
    "main_background_end": "#e9ecef",
    "splitter_handle": "#adb5bd",
    "splitter_handle_hover": "#4a90e2",
    "list_item_hover_background": "#e3f2fd",
    "list_item_hover_text": "#2c5aa0",
    "list_item_selected_background": "#4a90e2",
    "list_item_selected_text": "#ffffff",
}
fonts = {
    "system": get_system_font(),
    "monospace": get_monospace_font(),
    "default_size": f"{s(13)}pt",
    "tooltip_size": f"{s(9)}pt",
    "tab_size": f"{s(10)}pt",
    "menu_size": f"{s(10)}pt",
}
params = {

    "border_radius": f"{s(12)}px",
    "border_radius_small": f"{s(8)}px",
    "border_radius_very_small": f"{s(6)}px",
    "button_padding": f"{s(8)}px {s(24)}px",
    "button_min_width": f"{s(80)}px",
    "button_min_height": f"{s(36)}px",
    "icon_button_size": f"{s(30)}px",
    "main_window_width": str(s(1400)),
    "main_window_height": str(s(900)),
    "main_margin": str(s(16)),
    "main_spacing": str(s(16)),
    "tool_list_width": str(s(280)),
    "dialog_padding": f"{s(16)}px",
    "input_padding": f"{s(8)}px {s(12)}px",
    "input_margin": f"{s(8)}px {s(16)}px",
} 