# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('translations', 'translations'),
        ('favicon.ico', '.'),
        ('language_config.json', '.'),
        ('prompt.txt', '.'),
        ('sitecustomize.py', '.'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtSvg',
        'wct_modules.config',
        'wct_modules.i18n',
        'wct_modules.main_window',
        'wct_modules.parameters',
        'wct_modules.process',
        'wct_modules.process_tab',
        'wct_modules.real_terminal',
        'wct_modules.real_terminal_process',
        'wct_modules.styles',
        'wct_modules.templates',
        'wct_modules.theme',
        'wct_modules.tool_operation',
        'wct_modules.utils',
        'wct_modules.widgets',
        'wct_modules.promotion',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='WhiteCatToolbox',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='favicon.ico',
)