# .github/workflows/build.yml

# 1. 工作流名称
name: Build WhiteCatToolbox Cross-Platform

# 2. 工作流触发器
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# 3. 任务 (Jobs)
jobs:
  build:
    # 4. 策略矩阵 (Strategy Matrix)
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    # 5. 运行环境 (Runner)
    runs-on: ${{ matrix.os }}

    # 6. 步骤 (Steps)
    steps:
    # 步骤 6.1：签出代码
    - name: 签出代码 (Check out code)
      uses: actions/checkout@v4

    # 步骤 6.2：设置 Python 环境
    - name: 设置 Python 3.9 (Set up Python)
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    # 步骤 6.3：安装 Linux 系统依赖
    - name: 安装 Linux 依赖 (Install Linux dependencies)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libxcb-cursor0 xvfb

    # 步骤 6.4：安装 Python 依赖
    - name: 安装 Python 依赖 (Install Python dependencies)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # 步骤 6.5：使用 PyInstaller 构建 (Linux)
    - name: 使用 PyInstaller 构建 Linux (Build with PyInstaller - Linux)
      if: runner.os == 'Linux'
      run: |
        xvfb-run -a pyinstaller --noconfirm --onefile --windowed \
          --name "WhiteCatToolbox-${{ matrix.os }}" \
          wct.py

    # 步骤 6.6：使用 PyInstaller 构建 (非Linux)
    - name: 使用 PyInstaller 构建 (Build with PyInstaller)
      if: runner.os != 'Linux'
      run: |
        pyinstaller --noconfirm --onefile --windowed \
          --name "WhiteCatToolbox-${{ matrix.os }}" \
          wct.py

    # 步骤 6.7：打包 macOS 应用
    - name: 打包 macOS 应用 (Package macOS app)
      if: runner.os == 'macOS'
      run: |
        cd dist
        zip -r WhiteCatToolbox-macOS.zip "WhiteCatToolbox-${{ matrix.os }}.app"

    # 步骤 6.8：上传构建产物
    - name: 上传构建产物 (Upload build artifact)
      uses: actions/upload-artifact@v4
      with:
        name: WhiteCatToolbox-${{ matrix.os }}
        path: |
          dist/*
          !dist/WhiteCatToolbox-macOS.app